//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineShopEntities : DbContext
    {
        public OnlineShopEntities()
            : base("name=OnlineShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<checkout> checkouts { get; set; }
        public virtual DbSet<Checkout_Customer> Checkout_Customer { get; set; }
        public virtual DbSet<Checkout_Oder> Checkout_Oder { get; set; }
        public virtual DbSet<Checkout1> Checkout1 { get; set; }
        public virtual DbSet<CodeDiscount> CodeDiscounts { get; set; }
        public virtual DbSet<DongHo> DongHoes { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Item_Type> Item_Type { get; set; }
        public virtual DbSet<MayAnhvaMayQuayPhim> MayAnhvaMayQuayPhims { get; set; }
        public virtual DbSet<MayTinhvaLapTop> MayTinhvaLapTops { get; set; }
        public virtual DbSet<MevaBe> MevaBes { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SucKhoevaSacDep> SucKhoevaSacDeps { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TheThaovaDuLich> TheThaovaDuLiches { get; set; }
        public virtual DbSet<ThietBiGiaDung> ThietBiGiaDungs { get; set; }
        public virtual DbSet<ThoiTrangNam> ThoiTrangNams { get; set; }
        public virtual DbSet<ThoiTrangNu> ThoiTrangNus { get; set; }
        public virtual DbSet<Users_Acc> Users_Acc { get; set; }
    }
}
