//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id_SanPham { get; set; }
        public string Name { get; set; }
        public Nullable<int> Price { get; set; }
        public string Photo { get; set; }
        public string Details { get; set; }
        public int Id_Item { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Item_Type Item_Type { get; set; }
    }
}
